### ISSUE TITLE
Some zygomys in gemacs ?

### ISSUE THREAD

**Issue by ejemba** [glycerine/gemacs#2]
Hello @glycerine !

do you plan put some (a lot of) [Zygomys](https://github.com/glycerine/zygomys) in your implementation.

What make emacs great is the fact that it is greatly extensible. I think your lisp implementation is a good candidate.

I'm pretty sure you already think about it !

Sure it would be a good extension.

**Comment by glycerine** [comment]
Hi @ejemba, and thanks for the question.  I'm flattered that you
are familiar with zygomys and interested in gemacs.

I don't currently have any plans to do such an integration.

Its a rather large task, and I don't have need for it.

In a sense, too, emacs is already emacs. No sense in doing
alot of work to recreate it.

**Comment by ejemba** [comment]
> emacs is already emacs

ah ah you're right, I made a mistake on your motivations. :) 
Some try to have a better experience with an emacsish editor . I thought this could be the solution. Too bad for me ! 

@glycerine  What do you think of using go library/plugin capability to offer an SPI to extends gemacs then ?

**Comment by glycerine** [comment]
> What do you think of using go library/plugin capability to offer an SPI to extends gemacs then ?

Possibly. I think the short cut would be if `micro` could be simply be taught to use `emacs` key bindings.

See https://github.com/zyedidia/micro/issues/643

I didn't hear anything back yet, but I'm still hopeful that an emacs keybinding would become possible there. micro already has Lua builtin for extensions, and a ton of other nice features (syntax highlighting etc).

**Comment by glycerine** [comment]
Also, btw, see my https://github.com/gijit/gi project as a nice alternative to using Go's plugin system. It lets you write extensions in Go scripts, and have them interpreted at runtime.

**Comment by ejemba** [comment]
@glycerine what is good with emacs is not so much the shortcuts in themselves than the possibility to change them via configuration. 
I'll check all your links, thank you !
